# Site settings
author: Alina 
title: alinamalvin
header-img: img/home-bg.png
email: alinakornilova78@gmail.com
copyright_name: Alina 
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering Course Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alinamalvin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
